#!/bin/bash
################################################################################
# Script: 06_setup_automation.sh
# Description: Setup cron job for automatic daily data updates
#
# Parameters:
#   $1 - SCHEDULE (optional): Cron schedule
#        Options:
#          - "weekday_evening" (default): Mon-Fri at 7:00 PM
#          - "daily_evening": Every day at 7:00 PM
#          - "weekday_morning": Mon-Fri at 9:00 AM
#          - "custom": You will be prompted to enter custom cron schedule
#
# What it does:
#   1. Creates a cron-ready update script
#   2. Tests the script manually
#   3. Adds cron job to crontab
#   4. Sets up log rotation for old logs
#
# Cron Schedule Explanation:
#   Format: MIN HOUR DAY MONTH WEEKDAY COMMAND
#     - MIN: 0-59 (minute)
#     - HOUR: 0-23 (hour, 0 = midnight, 19 = 7 PM)
#     - DAY: 1-31 (day of month)
#     - MONTH: 1-12 (month)
#     - WEEKDAY: 0-6 (0 = Sunday, 1-5 = Mon-Fri)
#     - *: Any value
#
# Preset Schedules:
#   weekday_evening: 0 19 * * 1-5 (Mon-Fri 7:00 PM)
#   daily_evening:   0 19 * * *   (Every day 7:00 PM)
#   weekday_morning: 0 9 * * 1-5  (Mon-Fri 9:00 AM)
#
# Usage Examples:
#   # Setup with default (weekday 7 PM)
#   ./practices/06_setup_automation.sh
#
#   # Daily at 7 PM
#   ./practices/06_setup_automation.sh daily_evening
#
#   # Weekday morning
#   ./practices/06_setup_automation.sh weekday_morning
#
#   # Custom schedule (interactive)
#   ./practices/06_setup_automation.sh custom
#
# After Setup:
#   - Check cron jobs: crontab -l
#   - View logs: tail -f logs/cron_update.log
#   - Remove automation: crontab -e (delete the lines)
#
# Prerequisites:
#   - Data already collected (initial setup done)
#   - ClickHouse running
################################################################################

set -e  # Exit on error

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

SCHEDULE="${1:-weekday_evening}"

echo "==================================================="
echo "  Setup Automation (Cron Job)"
echo "==================================================="
echo ""

# Define cron schedule based on parameter
case "$SCHEDULE" in
    weekday_evening)
        CRON_TIME="0 19 * * 1-5"
        SCHEDULE_DESC="Monday-Friday at 7:00 PM"
        ;;
    daily_evening)
        CRON_TIME="0 19 * * *"
        SCHEDULE_DESC="Every day at 7:00 PM"
        ;;
    weekday_morning)
        CRON_TIME="0 9 * * 1-5"
        SCHEDULE_DESC="Monday-Friday at 9:00 AM"
        ;;
    custom)
        echo "Enter custom cron schedule (e.g., '0 19 * * 1-5' for Mon-Fri 7 PM):"
        read -p "Cron schedule: " CRON_TIME
        SCHEDULE_DESC="Custom: $CRON_TIME"
        ;;
    *)
        echo "Error: Invalid SCHEDULE '$SCHEDULE'"
        echo "Use: weekday_evening, daily_evening, weekday_morning, or custom"
        exit 1
        ;;
esac

echo "Schedule: $SCHEDULE_DESC"
echo "Cron: $CRON_TIME"
echo ""

# Step 1: Create the cron wrapper script
echo "[1/5] Creating cron wrapper script..."

CRON_SCRIPT="$PROJECT_DIR/scripts/update_stock_data.sh"

cat > "$CRON_SCRIPT" << 'EOFSCRIPT'
#!/bin/bash
################################################################################
# Auto-generated cron wrapper for stock data updates
# Generated by: 06_setup_automation.sh
################################################################################

# Absolute paths (required for cron)
PROJECT_DIR="PROJECT_DIR_PLACEHOLDER"
LOG_DIR="$PROJECT_DIR/logs"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
LOG_FILE="$LOG_DIR/cron_update.log"

# Create log directory if not exists
mkdir -p "$LOG_DIR"

# Log start
echo "========================================" >> "$LOG_FILE"
echo "Update started: $(date)" >> "$LOG_FILE"
echo "========================================" >> "$LOG_FILE"

# Ensure ClickHouse is running
cd "$PROJECT_DIR"
docker compose up -d >> "$LOG_FILE" 2>&1

# Wait for ClickHouse
sleep 5

# Run update
/usr/bin/python3 "$PROJECT_DIR/scripts/update_data.py" \
    --config "$PROJECT_DIR/config.yaml" \
    >> "$LOG_FILE" 2>&1

EXIT_CODE=$?

# Log result
echo "" >> "$LOG_FILE"
if [ $EXIT_CODE -eq 0 ]; then
    echo "✓ Update completed successfully: $(date)" >> "$LOG_FILE"
else
    echo "✗ Update failed with code $EXIT_CODE: $(date)" >> "$LOG_FILE"
fi
echo "========================================" >> "$LOG_FILE"
echo "" >> "$LOG_FILE"

exit $EXIT_CODE
EOFSCRIPT

# Replace placeholder with actual project directory
sed -i "s|PROJECT_DIR_PLACEHOLDER|$PROJECT_DIR|g" "$CRON_SCRIPT"

# Make executable
chmod +x "$CRON_SCRIPT"
echo "✓ Created: $CRON_SCRIPT"

# Step 2: Test the script
echo ""
echo "[2/5] Testing the update script..."
echo "(This will run one update to verify it works)"
echo ""
read -p "Press Enter to test, or Ctrl+C to skip..."

"$CRON_SCRIPT"

echo ""
echo "✓ Test successful! Check logs/cron_update.log for details"

# Step 3: Add to crontab
echo ""
echo "[3/5] Adding to crontab..."

# Check if cron job already exists
CRON_COMMENT="# Stock data auto-update"
if crontab -l 2>/dev/null | grep -q "update_stock_data.sh"; then
    echo "⚠ Warning: Cron job already exists"
    read -p "Replace existing job? (y/n): " REPLACE
    if [ "$REPLACE" != "y" ]; then
        echo "Skipping crontab update"
        exit 0
    fi
    # Remove old job
    crontab -l 2>/dev/null | grep -v "update_stock_data.sh" | crontab -
fi

# Add new job
(crontab -l 2>/dev/null; echo "$CRON_COMMENT"; echo "$CRON_TIME $CRON_SCRIPT") | crontab -

echo "✓ Cron job added: $SCHEDULE_DESC"

# Step 4: Setup log rotation
echo ""
echo "[4/5] Setting up log rotation..."

LOG_CLEANUP_CRON="0 2 1 * * find $PROJECT_DIR/logs -name 'cron_update*.log' -mtime +30 -delete"

if ! crontab -l 2>/dev/null | grep -q "cron_update.*-mtime"; then
    (crontab -l 2>/dev/null; echo "# Clean old update logs (monthly)"; echo "$LOG_CLEANUP_CRON") | crontab -
    echo "✓ Log rotation added (deletes logs older than 30 days)"
else
    echo "✓ Log rotation already configured"
fi

# Step 5: Display summary
echo ""
echo "[5/5] Summary"
echo "==================================================="
echo ""
echo "✓ Automation setup complete!"
echo ""
echo "Schedule: $SCHEDULE_DESC"
echo "Script:   $CRON_SCRIPT"
echo "Logs:     $PROJECT_DIR/logs/cron_update.log"
echo ""
echo "Verify cron jobs:"
echo "  crontab -l"
echo ""
echo "View logs:"
echo "  tail -f $PROJECT_DIR/logs/cron_update.log"
echo ""
echo "Remove automation:"
echo "  crontab -e"
echo "  (delete the lines with 'update_stock_data.sh')"
echo ""
echo "==================================================="
